### ISSUE TITLE
Feature Request: HipChat Integration

### ISSUE THREAD

**Issue by Heimschmiede** [howcani-project/howcani#36]
A HipChat Integration would be very great that sends a message to a specified hipchat room when a new question is asked in order to notify users and bring them back to the application.

related documenation:
API: https://www.hipchat.com/docs/apiv2/method/send_room_notification
Auth: https://www.hipchat.com/docs/apiv2/auth

**Comment by janbaer** [comment]
The HipChat Integration should be possible out of the box, since Github support webhooks, when someone creates a new issue or a comment to an issue. Sending a message to Hipchat is also supported.

**Comment by janbaer** [comment]
We activated the HipChat notifications in Github. It was only a 1 minute task
